"""Tables in the application schema.

``users`` and ``runs`` so far. ``threads`` and ``messages`` arrive with persisted
conversations, as additive migrations against this same base.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import StrEnum

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base


def _enum_column(enum: type[StrEnum], name: str) -> Enum:
    """A string-valued enum column.

    native_enum=False stores the value as VARCHAR rather than a Postgres ENUM
    type. Adding a member to a CHECK constraint is an ordinary migration;
    ``ALTER TYPE ... ADD VALUE`` cannot run inside a transaction, so it is not.

    create_constraint stays off because each table declares its constraint
    explicitly instead — one attached to the type is invisible to Alembic's
    autogenerate, which then reports it as dropped on every run.
    """
    return Enum(
        enum,
        name=name,
        native_enum=False,
        create_constraint=False,
        length=16,
        # Without this SQLAlchemy persists member *names* ("QUEUED").
        values_callable=lambda members: [member.value for member in members],
    )


def _check_values(column: str, enum: type[StrEnum], name: str) -> CheckConstraint:
    """The database-level backstop for anything writing outside the model."""
    allowed = ", ".join(f"'{member.value}'" for member in enum)
    return CheckConstraint(f"{column} IN ({allowed})", name=name)


class UserRole(StrEnum):
    """What a signed-in person may do.

    Two roles on purpose: this is an internal single-team tool, and a permission
    matrix nobody needs is a permission matrix nobody maintains.
    """

    ADMIN = "admin"
    MEMBER = "member"


class User(Base):
    """Someone who has signed in with a company Google account.

    Rows are created on first sign-in rather than invited ahead of time: the
    domain check already decides who is allowed, so a separate invitation step
    would only be a second list to keep in step with the first.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)

    # The identity Google asserts, lowercased on the way in. Unique because it is
    # how a returning user is recognised.
    email: Mapped[str] = mapped_column(String(320), nullable=False, unique=True)

    name: Mapped[str | None] = mapped_column(String(200), default=None)
    avatar_url: Mapped[str | None] = mapped_column(Text, default=None)

    role: Mapped[UserRole] = mapped_column(
        _enum_column(UserRole, "user_role"), nullable=False, default=UserRole.MEMBER
    )

    # Deactivation rather than deletion: a run refers to its owner, and history
    # that loses its author is worse than an account that cannot sign in. Checked
    # on every request, so revoking access takes effect at once.
    is_active: Mapped[bool] = mapped_column(nullable=False, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    last_login_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), default=None
    )

    runs: Mapped[list[Run]] = relationship(back_populates="user")

    __table_args__ = (_check_values("role", UserRole, "user_role"),)

    def __repr__(self) -> str:
        return f"<User {self.email} {self.role}>"


class RunStatus(StrEnum):
    """The lifecycle of a run, from accepted to settled.

    A ``StrEnum`` so the value is already the wire format used by the run event
    contract and the JSON API — no translation table to keep in step.
    """

    QUEUED = "queued"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"

    @property
    def is_terminal(self) -> bool:
        """True once the run has settled and its status can no longer change."""
        return self in _TERMINAL


_TERMINAL = frozenset({RunStatus.SUCCEEDED, RunStatus.FAILED, RunStatus.CANCELLED})


class Run(Base):
    """One agent execution.

    The durable record of a run. Redis holds the event log so a browser can
    replay or resume a stream, but that expires after an hour; this row is what
    remains, and it is what makes run status answerable after a restart.

    There is no column for the question asked: message content belongs to the
    ``messages`` table that arrives with persisted threads, and duplicating it
    here would only have to be removed again.
    """

    __tablename__ = "runs"

    # Generated by the API rather than the database: the caller is handed the id
    # in the response and needs it before the row is written.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    # Who asked. Not nullable: an unowned run could be read by anyone who knew
    # its id, so every query for a run filters on this.
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="RESTRICT"), nullable=False, index=True
    )

    status: Mapped[RunStatus] = mapped_column(
        _enum_column(RunStatus, "run_status"), nullable=False, index=True
    )

    # Why a run failed, in the words of whatever failed. Null on every other
    # outcome, including cancellation.
    error: Mapped[str | None] = mapped_column(Text, default=None)

    # Server-side defaults throughout: the API and the worker are separate
    # processes (separate containers in Compose), so taking every timestamp from
    # the database is the only way they cannot disagree by clock skew.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Set when a worker picks the run up, so queue wait is created_at -> started_at
    # and execution time is started_at -> finished_at.
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), default=None)

    user: Mapped[User] = relationship(back_populates="runs")

    __table_args__ = (_check_values("status", RunStatus, "run_status"),)

    def __repr__(self) -> str:
        return f"<Run {self.id} {self.status}>"
